### ISSUE TITLE
not hacs compliant

### ISSUE THREAD

**Issue by VictoriousCupid** [chomupashchuk/ariston-aqua-remotethermo-home-assistant#13]
Is it possible for you to make this compliant for HACS?

At the moment I get "Repostitory structure for 1.0.29 is not compliant"

**Comment by chomupashchuk** [comment]
it is possible, but it requires some work to align with: https://hacs.xyz/docs/publish/start
I have 7 integrations in total (few of them are being requested to be added) and also have some scripts for sync between PC and HA in Docker for the verification, which would also require updates. And it also would mean changes due to more strict release strategy, which I do not always follow and for now it is being done manually and as a result released package is not always synched with source files.

Since it is more of an improvement for users rather than a bug I do not prioritize it too much and I have to be in a mood to spend my free time on things like that. I do keep it in mind though.

**Comment by VictoriousCupid** [comment]
I absolutely agree that it is more of an improvement than a bug. 

And rest assured that the time you have put into this is much appreciated as it is. Hell, my electricity bill shows your work, so I am surely grateful. I have no clue of how to implement the thing I suggested, I would gladly have been of help in this regard. 

If there is however anything that can be done by me or anyone else, please mention it. If not, then not. I am stoked with the work you did as it is already!

Cheers!

**Comment by chomupashchuk** [comment]
The only thing that someone else can do is read documentation and let me know of what exactly does not comply. For example I know that structure has to be changed (move data to folder custom_componets) and json file created with configuration (which anyone can read and check what is mandatory and which values to use), but maybe there is more.

**Comment by chomupashchuk** [comment]
I'm trying with one of integrations first as a prototype:
https://github.com/chomupashchuk/delete-file-home-assistant

So if you'd like to help, you may check if repository can be added sucessfully. If succeeded, I can then proceed with other integrations.

**Comment by VictoriousCupid** [comment]
I opened https://github.com/chomupashchuk/delete-file-home-assistant in hacs no problem there went as expected.
Found it in hacs, could select versions without any issue. Used version 1.6. Went for install, seemed to go fine. 

After reboot, I would expect a folder alarm in custom_components. But I could not find anything related to delete-file-home-assistant in custom_components.

I tried to compare with other integrations but could not recognize anything significant. But again I am clueless and just report what I see.

**Comment by chomupashchuk** [comment]
I'm still not sure if delete integration works or not in HACS (already has brand in HA).

As for Ariston there is a delay (HACS checks brands in HA for logos and icons and it is still waiting):
https://github.com/home-assistant/brands/pull/2355

**Comment by VictoriousCupid** [comment]
I noticed there is a newer version available (1.0.32). Got the git link and put it in HACS. HACS -> intergrations -> custom repositories -> ad url  -> select "intergration"  -> add. 

Went as it should have. Installed the repo via HACS and rebooted. 

Now on version 1.0.32. And all files dated of the moment of install via HACS.

_/!\ One note: I did this while a previous version was already installed. /!\ 
/!\ So I think testing with a fresh install is still needed before closing is still needed /!\_

Side note. "Delete" was "updated" as well but no files available still in the custom_components folder.

**Comment by surenz** [comment]
I've tested it and it works. Just deleted previous '**aquaariston**' folder in **custom_components** and added it through HACS '**custom repository**' menu (hint: it's in the three dot menu at top right). Now I have one **aquaariston.git** and one **aquaariston** folders. All previous settings in the configuration.yaml were not touched. 

The only issue I had was that I needed do **STOP** server then start it from command line because the **RESTART** server was giving me error that the previous **aquaariston** integration is missing.

**Comment by chomupashchuk** [comment]
Yesterday brands for components got approved, which are used for the HACS.
So if it works then I close the ticket.
