### ISSUE TITLE
Improve the energy screens window

### ISSUE THREAD

**Issue by surenz** [chomupashchuk/ariston-aqua-remotethermo-home-assistant#14]
I think it will be useful to have more information about the (estimated) power consumption for the periods.

Currently the screen for Last day energy consumption appears like this:
![image](https://user-images.githubusercontent.com/5029229/111431274-4314fd00-8704-11eb-866f-a44e8cc45e44.png)

The periods for last day energy(24h) use are 12 so they are oddly made by Ariston to be measured consumption for last two hours, previous two hours and so on.
The periods for last week are divided by 7 so it's easy there.
The periods for the month are 15 so again 2 days means one period.
The periods for the year are 12 at last :)

Is there a way those periods to be calculated and shown as exact time (day periods), day (week, month periods), month (year periods)?
Thanks.

**Comment by chomupashchuk** [comment]
It is technically possible to read different time periods, fetch current time and calculate all previous periods and output. Still there are details like time drifting (simplest is to calculate on current time/date but it means that 2 hour step would result in reports like 1, 3, 5 ... and the next hour as 2, 4, 6 ... ). Than there is option to keep historical data and compare results to avoid that drifting, which brings additional complexity, or have strict rounding, which might bring unexpected jumps due to possible lack of synchronization.
Lately I Have very little spare time and I get more and more requests (I don't get anything from these project), so unless there'll be contributors I have doubts that it will be implemented soon or ever.
