### ISSUE TITLE
Velis and controling by temp

### ISSUE THREAD

**Issue by krzysiek2788** [chomupashchuk/ariston-aqua-remotethermo-home-assistant#20]
Hi,
Do you know why in Velis setting up temperature isn't working now? Did they changed something and it is problem now? In Ariston app setting up temperature manually is working fine also I had script in Home Assistant and it was working before. I rather control boiler via temperature than showers I need.

**Comment by krzysiek2788** [comment]
Ok small correction on old soft 1.0.29 setting temperature manually is working fine, so I'm wondering why did you delete that option in Velis model?

**Comment by chomupashchuk** [comment]
I did not delete any part on purpose. I do not have boiler supporting this integration and have no possibility to verify even the smallest of changes. I have no idea if anything changed from Ariston side or if I accidently made a mistake and I plan to stop support of this integration as a result. I simply get a very vague desription and have to start asking for specific data, trying to figure things out, make prototypes, send them for tests etc, and coordinate some actions, and it takes a lot more time than if I had equipment myself.

I can have a quick look (if it would take very little time) but I plan to stop any updates of this integration due to lack of test environment and lack of benefit for me (moral or financial).

**Comment by krzysiek2788** [comment]
Oh I see in this case I will try to compare it my self and try to improve it. Thank you for you answer :)

**Comment by chomupashchuk** [comment]
I do not see visually in code the difference between 2 versions how it can affect temperature setting.
One of the updates was changing unique id, which means duplication of entities (HA might keep old oneas and create a new one with `2` at the end). Also there was change in setting statuses and having enents reporting introduced for api in general, but not sure how it could have affected the setting part, where REST request should be the same.

Without debugging on actual requests responces it is hard to figure out for me the possible cause.

**Comment by krzysiek2788** [comment]
Ok I understand. What if I can provide you what you need to check this and in future I can also provide you everything what you need to continue support of this add-on.

**Comment by chomupashchuk** [comment]
The fastest for me is to have access to the boiler to try and set temperature and check the response and pinpoint place where something goes wrong (e.g. skipped configuration attempt due to specific check, or if something changed lately in the requests).
For example in similar integration request to change data receives positive responces in some cases even though nothing happens, some changes in sensors could result in assumptions that change is not needed (already correct values are set) or that some daya is incorrect and changes are skipped. Considering amount of data and type of issue it is hard to pinpoint with simple code review.
By the way, is Velis in your case (application) uses number of showers or temeparture as an input? - it seems like there are differences in Velis models as well.
Did you try using older version if it indeed works?

**Comment by krzysiek2788** [comment]
In my option when I use 1.0.35 and use option type: velis I do not have option to change temeprature in entity: water_heater.aqua_ariston
When I change to 1.0.29 I have that option and it is working. On my phone in Aqua Ariston I have temp regulation here is screen from mobile phone app:
![Screenshot_20210504_135709_com remotethermo velis](https://user-images.githubusercontent.com/61471407/117000064-cc968380-ace0-11eb-808f-855981110d27.jpg)

**Comment by chomupashchuk** [comment]
Do you happen to have 2 water_heater entities by any chance? - just to rule out duplication I have mentioned.
What is the state and attributes of the water_heater?
Here I'm a bit confused, can you change temepartures by 1 degree C? Does it mean your model should behave as Lydos?

I have compared __init__.py and water_heater.py modules updates between 1.0.29 and 1.0.35 and nothing interesting there (logging and unique ID). So if there is a fault then it is more likely in aristonaqua.py.
If there is no duplication and state is "unavaialble" for example, then dhw_available is is set to False in the API, which has to be investigated further. In that case values used in method _set_statuses has to be checked (there are checks on line 681 if it is model VELIS and no yet shower data is available (uses number of showers as input and does not support temeparture as input) then DHW is not yet available). If that is the case, then _ariston_shower_data would have to be checked for validity (do we receive valid reply for the request or if we get an exception that results in logging info/warning).
I'm asking about Velis type as the first model of Velis I have worked with did not support requests to set temperatures and used number of showers instead towards Ariston server, while Lydos and Lydos Hybrid use temepartures to set instead of number of showers (but they have different patterns in requests comapring one to another). I got info that some Velis models behave similar to Lydos. Converting of showers to internal temepartures for specific Velis was done as a prototype and I did not have possibility to test it properly as it was enough for the guy, who provided me with the access. That is why I ask about the configuration to understand better.

**Comment by chomupashchuk** [comment]
This is the reason why I don't like maintaining this integration as I do not understand fully the situation and i have to ask a bunch of questions, sometimes provide with prototypes that gather more data (or at least set logging level to DEBUG and store_config_files to true and provide with specific files and possibly test possible solutions). That interaction takes time as I ask at one time, get responce at another, have to come back to this isse again, probably send data and wait for reply again, and it ofetn means multiple days of interaction, while having access to hardware I could simply spend once maybe 30 minutes to set traces, find the cause and make a solution and test it. But with other partly not only it spreads in time it also means I have to spend additional time on explanations on what I need, which could mean not 30 minutes but few hours of my time.

**Comment by krzysiek2788** [comment]
Regarding duplication yes I had that, one was unavailable and other one have only to set program no temperature to setup. In Ariston app I can set temperature every 1 degree. Also I tried type: Lydos but it had some issue as well. I can send you now whole folder of logs from old version, update to new one and after it sync I can try to set temperature and send you log folders also screens with type: velis and type: lydos. I know it would be easier to have access to it by you but it will be needed to give you serial number to register it on your account or give you permission  to my Home Assistant instance or share my Ariston account with you.

**Comment by chomupashchuk** [comment]
If you can set temperature every 1 degree in the app then type lydos should work in your case (unless it is another kind of Velis behavior), so it is confusing to me how it actually worked.
To access boilers I used provided credentails to Ariston (some used temporary password while I made my tests), but I understand that it is not the information people should share lightly, and I suspect that I would need constant contact to ask if it is OK to test something on specific hardware and when it is possible to do (some wanted to be present at home and to know exactly what I plan to do), if people would actually agree to let me use it in the first place. I wouldn't want to share my credentials and thus why should I ask others to do so?

By the way, which logs exactly do you mean? There is HA log, where data is written depending on logging level in the integration, and there are also generated files if store_config_files is set to True (some of them also carry plant ID and I don't rememeber, but i guess one of them has password as well), where some files provide data on what is being sent to the server and some provide data on how it replied.
Note that logging does not include some api data.

Which state and attributes are for the water heater? - it is strange if water heater is available and allows change of program but not the temperature. Maybe temperatures are not set within the sensors that cause it. Did you check sensors current_temperature and required_temperature?

**Comment by krzysiek2788** [comment]
I don't minde sharing temp password for you even now. on FB or via mail

**Comment by krzysiek2788** [comment]
Even more I can give you access to the boiler any time you need. But it will be good to contact via FB or What's up or other way which is fast. I don't have issue changing password to temp one when you need to check something I know it is for "greater good" ;)

**Comment by chomupashchuk** [comment]
I have whatsup (+380971537913) and gmail (chomu.nattsol@gmail.com), for sure personal data should not be included here. In general i prefer to use reading of data as much as possible during troubleshooting and updates (check that sensors have valid data). Update of configuration is a different story, I prefer to check if it's fine or not.

Just an info that Ariston has easy to read passwords by analyzer, so good to keep it different from all others for security reasons, also if you share it with someone good to not have a common ones.

**Comment by krzysiek2788** [comment]
Ok. I think we can close this case and continue on What's up I text you with my login and test password for you. I will only need to have info from you once you would like to test something and after you finish so I can change password ;)
