### ISSUE TITLE
connection issues

### ISSUE THREAD

**Issue by VictoriousCupid** [chomupashchuk/ariston-aqua-remotethermo-home-assistant#28]
Logs:
1#

> This error originated from a custom integration.
> 
> Logger: custom_components.aquaariston.aristonaqua
> Source: custom_components/aquaariston/aristonaqua.py:1554
> Integration: AquaAriston (documentation, issues)
> First occurred: 10:03:38 (22 occurrences)
> Last logged: 10:28:50
> 
> <custom_components.aquaariston.aristonaqua.AquaAristonHandler object at 0x7f0f737c6fb0> Retrying in 72.0 seconds

2#

> This error originated from a custom integration.
> 
> Logger: custom_components.aquaariston.aristonaqua
> Source: custom_components/aquaariston/aristonaqua.py:978
> Integration: AquaAriston (documentation, issues)
> First occurred: 10:00:51 (29 occurrences)
> Last logged: 10:28:51
> 
> <custom_components.aquaariston.aristonaqua.AquaAristonHandler object at 0x7f0f737c6fb0> Unexpected reply during login: 404
> 

3#

> This error originated from a custom integration.
> 
> Logger: custom_components.aquaariston.aristonaqua
> Source: custom_components/aquaariston/aristonaqua.py:1656
> Integration: AquaAriston (documentation, issues)
> First occurred: 10:00:51 (29 occurrences)
> Last logged: 10:28:51
> 
> Connection errors: 25
> Connection errors: 26
> Connection errors: 27
> Connection errors: 28
> Connection errors: 29

4#

> This error originated from a custom integration.
> 
> Logger: custom_components.aquaariston.aristonaqua
> Source: custom_components/aquaariston/aristonaqua.py:1679
> Integration: AquaAriston (documentation, issues)
> First occurred: 10:00:51 (29 occurrences)
> Last logged: 10:28:51
> 
> ariston action nok for _get_main: Login unexpected reply code

configuration.yaml:

```
aquaariston: 
  username: **@gmail.com
  password: ***
  type: "lydos_hybrid"
  polling: 1.2
  store_config_files: true 
  switches:
    - power
  sensors:
    - current_temperature   
```
  
Connection with app no issue.

if there is any additional info that I can provide please tell me. Also, I can give access to my boiler if that helps.

**Comment by kbrelins** [comment]
I have the same issue in my HA :(

**Comment by VictoriousCupid** [comment]
> I have the same issue in my HA :(

Can you post logs and yaml to compare?

**Comment by niesamowitysmyk** [comment]
#Me too on velis integration: https://github.com/chomupashchuk/ariston-aqua-remotethermo-home-assistant

**Comment by VictoriousCupid** [comment]
Both of you get the 404 error in logs?

**Comment by VictoriousCupid** [comment]
> It seems that Ariston replies a 404 on https://www.ariston-net.remotethermo.com/Account/Login 

That link redirects me to https://www.ariston-net.remotethermo.com/R2/Account/Login

**Comment by tarchia** [comment]
This is because https://www.ariston-net.remotethermo.com/R2/Account/Login return the only json:{"ok":true,"redirectUrl":null,"message":"","debugMessage":""}

that can't be parsed by self._get_plant_id(resp).

**Comment by VictoriousCupid** [comment]
That goes above my ability to fix I'm afraid. Does anyone have any suggestions? more than willing to f* up my setup if it brings us closer to fixing this issue.

**Comment by tarchia** [comment]
This is a very quick and dirty solution:

```
def _login_session(self):
         """Login to fetch Ariston Plant ID and confirm login"""
         if not self._login and self._started:
-            url = self._url + '/Account/Login'
+            url = self._url + '/R2/Account/Login'
             login_data = {"Email": self._user, "Password": self._password}
             try:
                 with self._token_lock:
@@ -978,6 +978,19 @@ class AquaAristonHandler:
                 self._LOGGER.warning('%s Unexpected reply during login: %s', self, resp.status_code)
                 raise Exception("Login unexpected reply code")

+            try:
+                    resp = self._session.get(
+                           url = self._url + '/R2/Home',
+                            auth=self._token,
+                            timeout=self._HTTP_TIMEOUT_LOGIN,
+                            verify=True)
+            except requests.exceptions.RequestException:
+                self._LOGGER.warning('%s Checking plantid error', self)
+                raise Exception("Checking gateways error")
+            if resp.status_code != 200:
+                self._LOGGER.warning('%s Checking plantid error', self)
+                raise Exception("Checking plant error")
+
             plant_id = self._get_plant_id(resp)

```

**Comment by maciejka104** [comment]
> I've succeeded to make this integration to work again with this workaround:
> 
>     1. As suggested above change the login url on line 956 of _aristonaqua.py_ with updating it from
>        `url = self._url + '/Account/Login'` to
>        `url = self._url + '/R2/Account/Login'`
> 
>     2. As the __get_plant_id_ does not work anymore just delete the method and write the _plant_id_ directly in the __login_session_ method on line 981 (before deleting the _get_plant_data) between double quotes.
> 
> 
> The _plant_id_ is easily found after logging the site with your credentials https://www.ariston-net.remotethermo.com/ and watch the id after https://www.ariston-net.remotethermo.com/R2/Plant/Index/ I suggest even to expose the _plant_id_ in the parameters needed for the integration to work (unfortunately my skills are not enough to make it) because the method to extract it from the login page seems very fragile (and literally with many ifs).

Could you explain or show an example regarding point 2?

**Comment by chomupashchuk** [comment]
My boiler supports other integration, so I cannot check things myself.
Can you try changing data in `_login_session` by replacing url value with `f'{self._url}/R2/Account/Login?returnUrl=%2FR2%2FHome'` and login_data with `login_data = {"email": self._user, "password": self._password, "rememberMe": False, "language": "English_Us"}`.

The integration was mainly based on Android application behavior except from login process and automated plant id identification. I do not know how redirection would work for this specific integration after successful login as the above changes are for the other integration for my boiler.

By the way, if things would get too complex, there is already default GW (plant id) parameter in the integration and code can be changed to use it instead of updating code directly for every single user (just replace `plant_id = self._default_gw`).

I can suggest the following:
- you may try to check which updates would work to make automated plant id identification work. If the way found, I can include code and release new version.
- if automated identification will not work then I can simply update code to make gateway (plant id) input as mandatory

**Comment by surenz** [comment]
@chomupashchuk Yesterday when I tried to troubleshoot the issue I've put a logger to show me what string comes for resp.url and it was the login page URL. So that's why your patterns in _get_plant_id  don't work.

I've tried what you suggested above (just changed False to false) in Postman and it loads an HTML page with the appliance data. The Url is the right one but it makes many redirects until hitting it (Code 302).

**Comment by chomupashchuk** [comment]
try updated version

**Comment by surenz** [comment]
Tried new update 1.0.50 with Lydos heater and the integration works correctly again. No errors in logs neither. Thanks for immediate reaction @chomupashchuk

**Comment by maciejka104** [comment]
@[chomupashchuk](https://github.com/chomupashchuk) 
Works OK!

**Comment by niesamowitysmyk** [comment]
Great news! Could you also improve "Velis" integration?
https://github.com/chomupashchuk/ariston-aqua-remotethermo-home-assistant

It works - thank You!

**Comment by VictoriousCupid** [comment]
Thanks a million, @chomupashchuk !
I am glad you could fix it this quickly! My offer keeps standing about my credentials if it helps anyway.

Cheers!
