### ISSUE TITLE
_get_cleanse No json detected

### ISSUE THREAD

**Issue by kovacsguido** [chomupashchuk/ariston-aqua-remotethermo-home-assistant#9]
I found this warning in the Home Assistant logs, after I installed the 1.0.24 version of this component (this warning repeats every two minutes, continuously):

Logger: custom_components.aquaariston.aristonaqua
Source: custom_components/aquaariston/aristonaqua.py:1108
Integration: aquaariston
First occurred: 12:18:50 (12 occurrences)
Last logged: 12:40:50

<custom_components.aquaariston.aristonaqua.AquaAristonHandler object at 0x7fd5f8e74640> _get_cleanse No json detected

**Comment by chomupashchuk** [comment]
Which boiler model do you have? Does it actually support cleanse function?

Based on short description it seems that HTML is being returned for a specific request for some reason instead of JSON.
For example I was told that Lydos Hybrid does not support it. I have none of mentioned boilers for the integration and I put it up together based on data provided by others. So if your boiler does not support cleanse function it is good that you remove all sensors, binary_sensors and switches related to cleanse function, which should automatically disable sending of a specific request.
If your boiler does support cleanse function and it works from the android app but not an integration then it is another story and additional data has to be collected.

**Comment by kovacsguido** [comment]
My boiler is an Ariston Velis EVO Wifi 50.
This model does support the cleanse (antilegionella) function, I have seen it work several times.

But this function isn't available in mobil app (on my iPhone) or the device control panel.
This is an automatically function at this model, it turn on at:
- the boiler first power on,
- after each power failure,
- and if the boiler always operates at a temperature below 55 ° C, then once a month

**Comment by chomupashchuk** [comment]
Integration simulates requests from mobile app (I used fiddler to listen to the requests and simulate them). So if it is not available in the application it will not be available in the integration.
Some models did have cleanse function in application and thus it is included in requests but I have no data to identify the support for specific model (for example if it is the case for all Velis or not) and the simplest is to disable sensors and switches by the user that utilize specific problematic request (no sensors for the request means that integration shall omit sending that request, which means less requests in a loop to send, which means faster feedback).

**Comment by chomupashchuk** [comment]
From what I see only 'antilegionella_set_temperature' utilizes that request, so if it is not included in your app, probably good to comment or remove it from configuration.yaml

**Comment by chomupashchuk** [comment]
Closed due to lack of activity
